### PR TITLE
Feature/add player nickname to mt ts

### PR DESCRIPTION
**Pull request by brunetton**
I think it would be default conf for all games formats; I don't see how HUD could be usable without players names

### CODE REVIEW

**Comment by jejellyroll-fr** [comment]
tx Bruno ;)

**Comment by sf-87** [comment]
HUD config is something highly personal, luckily it does not overwrite if already exists, but should not be changed basing on your feelings.
If you keep the stats near the relative seat (as should be) its usable without players name, hence you're "stealing" one spot that can be used for useful stats while playing

**Comment by brunetton** [comment]
> HUD config is something highly personal, luckily it does not overwrite if already exists, but should not be changed basing on your feelings.

100% agreed

> If you keep the stats near the relative seat (as should be) its usable without players name, hence you're "stealing" one spot that can be used for useful stats while playing

Yes, in theory it should be like this; but
- the algorithm (is there any ?) that is responsible for placing HUD stats is not very "clever": each time I resize the table, even by a very little amount, all my stats are projected anywhere on the screen and it's a total mess. I've to replace everything 
- as it's easier to remove things instead of adding things, I've the feeling that newcomers would prefer having to remove that they don't use from a "complete" HUD instead of adding things (maybe I'm wrong)
- for now the only way to edit HUD is by editing XML conf file and I've the feeling that it's easier that way (deleting instead of adding)

You're free to merge or not this PR of course

For a quite far future I'd love to let people share their HUDs, why not hosting a place (Git repo ?) where people can add HUDs and download them, with at least a preview of what it looks like

**Comment by sf-87** [comment]
As I'm using fpdb since 2010 I can suggest you some things:

- resizing and moving issues are os oriented, maybe for once I'm lucky with Windows, but in case you want to reset positions simply "restart this hud" from the table menu will do the trick.
- I think there's something like 80+ stats to choose from, so a complete HUD is unusable. I personally have 12 and half of them are situational for post-flop action
- I don't remember when I created my conf if I found the info in the file or in a wiki, but should be easier to just explain what "_stat_name" is (ie. ffreq1 = fold frequency on flop) and let people choose his own configuration. People who use tracking already knows what stats want to see (otherwise he's just losing time and money).

**Comment by brunetton** [comment]
Thanks for the hints

> resizing and moving issues are os oriented, maybe for once I'm lucky with Windows, but in case you want to reset positions simply "restart this hud" from the table menu will do the trick.

Unfortunately it doesn't changed anything for me

> I think there's something like 80+ stats to choose from, so a complete HUD is unusable. I personally have 12 and half of them are situational for post-flop action

I put "complete" between quotes, I was talking about the default HUD in fact.

> I don't remember when I created my conf if I found the info in the file or in a wiki, but should be easier to just explain what "_stat_name" is (ie. ffreq1 = fold frequency on flop) and let people choose his own configuration. 

Of course, I planned to add it onto the Wiki (or somewhere else but I think Wifi is a good way to document 

> People who use tracking already knows what stats want to see (otherwise he's just losing time and money)

Poker isn't a waste of money when beginning ? But how to become a good player without being a beginner before ? Okay it's 100% not related with the subject :)

**Comment by sf-87** [comment]
> Unfortunately it doesn't changed anything for me

Strange, must be something wrong in the xxTable.py of your OS then...

> Poker isn't a waste of money when beginning ? But how to become a good player without being a beginner before ? Okay it's 100% not related with the subject :)

A beginner should never use a tracker like fpdb, he doesn't know what to do. And a good player that hasn't studied how to use a tracker should never use it as well, or he will do the wrong choices with the info that doesn't understand :)

**Comment by brunetton** [comment]
> A beginner should never use a tracker like fpdb, he doesn't know what to do. And a good player that hasn't studied how to use a tracker should never use it as well, or he will do the wrong choices with the info that doesn't understand :)

One point for you ! You're 100% correct

**Pull request merged**
